services:
  survey_db:
    container_name: survey_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DATABASE}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    volumes:
      - postgre-data:/var/lib/postgresql/data
    networks:
      - private

  survey_app:
    container_name: survey_app
    build:
      context: https://github.com/betagouv/tell-me.git#main
      args:
        DATABASE_URL: ${TELLME_DATABASE_URL}
    restart: always
    environment:
        DATABASE_URL: ${TELLME_DATABASE_URL}
        EDDSA_PRIVATE_KEY: ${TELLME_EDDSA_PRIVATE_KEY}
        NEXT_PUBLIC_EDDSA_PUBLIC_KEY: ${TELLME_NEXT_PUBLIC_EDDSA_PUBLIC_KEY}
    volumes:
      - tellme-assets:/app/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.survey.entrypoints=websecure"
      - "traefik.http.routers.survey.rule=Host(`survey.lab-agora.fr`)"
      - "traefik.http.routers.survey.tls.certResolver=lets-encrypt"
    networks:
      - private
      - proxy
    depends_on:
      - survey_db

volumes:
  postgre-data:
  tellme-assets:

networks:
  private:
    external: false
  proxy:
    external: true
