version: "3.9"

services:
  survey_db:
    container_name: survey_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DATABASE}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    volumes:
      - postgre-data:/var/lib/postgresql/data
    networks:
      - private

  survey_db_legacy:
    container_name: survey_db_legacy
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
      MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
    volumes:
      - ./scripts/docker/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
      - mongodb-data:/data/db
    networks:
      - private

  survey_app:
    container_name: survey_app
    build:
      context: https://github.com/betagouv/tell-me.git#main
      args:
        DATABASE_URL: ${TELLME_DATABASE_URL}
        DB_URL: ${TELLME_DB_URL}
        NEXT_PUBLIC_RSA_PUBLIC_KEY: ${TELLME_NEXT_PUBLIC_RSA_PUBLIC_KEY}
    restart: always
    environment:
        DATABASE_URL: ${TELLME_DATABASE_URL}
        DB_URL: ${TELLME_DB_URL}
        NODE_ENV: ${TELLME_NODE_ENV}
        RSA_PRIVATE_KEY: ${TELLME_RSA_PRIVATE_KEY}
    volumes:
      - tellme-assets:/app/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.survey.entrypoints=websecure"
      - "traefik.http.routers.survey.rule=Host(`survey.lab-agora.fr`)"
      - "traefik.http.routers.survey.tls.certResolver=lets-encrypt"
    networks:
      - private
      - proxy
    depends_on:
      - survey_db
      - survey_db_legacy

volumes:
  mongodb-data:
  postgre-data:
  tellme-assets:

networks:
  private:
    external: false
  proxy:
    external: true
