version: "3.9"

services:
  db:
    container_name: survey_db
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
      MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
    volumes:
      - ./scripts/docker/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
      - mongodb-data:/data/db

  app:
    container_name: survey_app
    build: https://github.com/betagouv/tell-me.git#main
    restart: always
    environment:
        DB_URL: ${TELLME_DB_URL}
        NODE_ENV: ${TELLME_NODE_ENV}
        PORT: ${TELLME_PORT}
        RSA_PRIVATE_KEY: ${TELLME_RSA_PRIVATE_KEY}
        NEXT_PUBLIC_RSA_PUBLIC_KEY: ${TELLME_NEXT_PUBLIC_RSA_PUBLIC_KEY}
    ports:
      - ${TELLME_PORT}:${TELLME_PORT}
    depends_on:
      - db

volumes:
  mongodb-data:
