services:
  db:
    container_name: survey_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgre-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - 5432:5432
    networks:
      - private

  app:
    container_name: survey_app
    build:
      context: https://github.com/betagouv/tell-me.git#main
      args:
        DATABASE_URL: ${TELLME_DATABASE_URL}
        EDDSA_PRIVATE_KEY: ${TELLME_EDDSA_PRIVATE_KEY}
        NEXT_PUBLIC_EDDSA_PUBLIC_KEY: ${TELLME_NEXT_PUBLIC_EDDSA_PUBLIC_KEY}
    restart: always
    environment:
      DATABASE_URL: ${TELLME_DATABASE_URL}
      EDDSA_PRIVATE_KEY: ${TELLME_EDDSA_PRIVATE_KEY}
      NEXT_PUBLIC_EDDSA_PUBLIC_KEY: ${TELLME_NEXT_PUBLIC_EDDSA_PUBLIC_KEY}
    volumes:
      - tellme-assets:/app/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.survey.entrypoints=websecure"
      - "traefik.http.routers.survey.rule=Host(`survey-labagora.e-cancer.fr`)"
      - "traefik.http.routers.survey.tls=true"
    networks:
      - private
      - proxy
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgre-data:
  tellme-assets:

networks:
  private:
    external: false
  proxy:
    external: true
